[project]
name = "lsp-multiplexer"
version = "0.1.0"
description = "Simple LSP server multiplexer"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["tomli"]

[project.scripts]
lsp-multiplexer = "lsp_multiplexer:main"
